spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Product
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: create

api:
  placeholder: https://jsonplaceholder.typicode.com
server:
  port: 8081
